### ISSUE TITLE
upcoming `sf` breaks `geomultistar`

### ISSUE THREAD

**Issue by edzer** [josesamos/geomultistar#6]
See https://github.com/r-spatial/sf/blob/main/NEWS.md : in upcoming `sf`, `st_layers()` returns an object of class `c("sf_layers", "data.frame")`; this breaks a test in `geomultistar`:
```r
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  > 
  > test_check("geomultistar")
  Deleting source `/tmp/RtmpYa3CfM/city.gpkg' failed
  Writing layer `city' to data source `/tmp/RtmpYa3CfM/city.gpkg' using driver `GPKG'
  Writing 9 features with 19 fields and geometry type Point.
  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 56 ]
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-dimensional_query_save.R:46:3'): dimensional_query_save works ──
  class(l) not equal to "sf_layers".
  Lengths differ: 2 is not 1
  
  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 56 ]
  Error: Test failures
  Execution halted
```
please modify the test and resubmit to CRAN.  

If you use `inherits(l, "sf_layers")` it will work for both current and upcoming versions of `sf`.

**Comment by josesamos** [comment]
Hi! I just modified it and submitted it to CRAN. I apologize for any inconvenience this may have caused.

**Comment by edzer** [comment]
Thanks,

> I apologize for any inconvenience this may have caused.

Not at all!
